namespace ParquetMapper.Model;

public enum AmdiColumn
{
    ProductId = 0,
    BaseProductId,
    AmdmStatusCode,
    StyleId = 3,
    Dcs = 8,
    Catalogs = 9,
    Categories = 10,
    ItemId = 11,
    ItemProductId = 12,
    ItemAmdmStatusCode = 13,
    ItemBaseItemId = 14,
    ItemSize = 15,
    ItemFSS = 16,
    IsDiscountable = 17,
    IsTaxable = 18,
    IsDeleted = 19,
    IsSmartExclusion = 20,
    ItemDaxVendorItemIds = 21,
    IsSellable = 22,
    ItemSortOrder = 23,
    ItemMaxQPO = 24,
    ItemCost = 25,
    ItemUpc = 26,
    ItemEan = 27,
    ItemKbc = 28,
    ItemJcpSku = 29,
    ItemJcpPPL = 30,
    ItemDtgSku = 31,
    ItemWidth = 32,
    ItemHeight = 33,
    ItemWeight = 34,
    ItemLength = 35,
    ItemPsd = 36,
    PvName = 37,
    PvValue = 38,
    PvDataType = 39,
    PvLocale = 40,
    PvORGId = 41,
    PvBSO = 42,
    PvMdmId = 43,
    OPvORGId = 44,
    OPvName = 45,
    OPvValue = 46,
    OPvDataType = 47,
    OPvLocale = 48,
    OPvMdmId = 49,
    ProductGroups = 50,
    MerchClass = 51,
    Cost = 52,
    Sizes = 53
}